services:
  - type: web
    name: hostel-marketplace-api
    env: python
    buildCommand: "cd backend && chmod +x build.sh && ./build.sh"
    startCommand: "cd backend && gunicorn config.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
