# Generated by Django 5.1 on 2026-05-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
