# Generated by Django 5.1 on 2026-05-23 11:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_seed_categories'),
        ('products', '0003_add_sold_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_available', 'is_sold', '-created_at'], name='products_pr_is_avai_aa4ff9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', '-created_at'], name='products_pr_categor_546c8c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['seller'], name='products_pr_seller__1bcc9b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_sold', 'sold_at'], name='products_pr_is_sold_ba995a_idx'),
        ),
    ]
